[package]
name = "github-notifier-rs"
version = "0.1.0"
authors = ["kunicmarko20 <kunicmarko20@gmail.com>"]
edition = "2018"

[dependencies]
libappindicator = "0.4.0"
glib= "0.5.0"
gtk= "0.4.0"
gtk-sys= "0.6.0"
notify-rust = "3"
webbrowser= "0.4.0"
